name: build Infrastructure
description: "Run `pnpm install`"

on:
  workflow_call:
  
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 7.1.5

    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
