name: lint Infrastructure

on:
  workflow_call:
  
jobs:
  lint:

    name: lint
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./infrastructure
        shell: bash


    steps:
    - uses: actions/checkout@v3

    - name: Cache NPM dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-npm-cache-

    - name: Install NPM dependencies
      run: npm install
    - run: npm run lint
